# Generated by Django 6.0.6 on 2026-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
